import type { Metadata } from 'next'
// import {WindSong} from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const windsong = WindSong({
//   subsets : ['latin'],
//   variable: '--font-windsong',
//   weight: '400',
// })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
